version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: shopping-cart-db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shopping-net

  redis:
    image: redis:6-alpine
    container_name: shopping-cart-redis
    ports:
      - '6379:6379'
    networks:
      - shopping-net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopping-cart-backend
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - DATABASE_HOST=postgres
      - REDIS_HOST=redis
    networks:
      - shopping-net


volumes:
  postgres_data:

networks:
  shopping-net:
    driver: bridge
